config/routes.rb
Rails.application.routes.draw do
  resources :techniques do
    collection do
      get 'search'
    end
  end

  get 'setting/index'
  get 'setting/set'

  root to: "top#index"

  get 'top/index'

end

app/models/function.rb
class Function < ActiveRecord::Base
  belongs_to :function_category
  has_many :techniques, :dependent => :destroy

  scope :purpose1, -> { where(purpose1: true) }
  scope :purpose2, -> { where(purpose2: true) }
  scope :purpose3, -> { where(purpose3: true) }
  scope :purpose4, -> { where(purpose4: true) }

end

app/models/function_category.rb
class FunctionCategory < ActiveRecord::Base
  has_many :functions
  has_many :techniques, through: :functions
end

app/models/part.rb
class Part < ActiveRecord::Base
  belongs_to :part_category
  has_many :techniques, :dependent => :destroy

  scope :of_supported, -> { where(openflow: true) }
  scope :netconf_supported, -> { where(netconf: true) }
  scope :ovsdb_supported, -> { where(ovsdb: true) }

  scope :written_by_c, -> { where(lang1: true) }
  scope :written_by_ruby, -> { where(lang2: true) }
  scope :written_by_python, -> { where(lang3: true) }
  scope :written_by_java, -> { where(lang4: true) }
end

app/models/part_category.rb
class PartCategory < ActiveRecord::Base
  has_many :parts
  has_many :techniques, through: :parts
end

app/models/search/base.rb
class Search::Base
  include ActiveModel::Model
  include ActiveModel::Validations::Callbacks

  def contains(arel_attribute, value)
    arel_attribute.matches("%#{escape_like(value)}%")
  end

  def escape_like(string)
    string.gsub(/[\\%_]/) { |m| "\\#{m}" }
  end

  def value_to_boolean(value)
    ActiveRecord::ConnectionAdapters::Column.value_to_boolean(value)
  end
end

app/models/search/technique.rb
class Search::Technique < Search::Base
  ATTRIBUTES = %i(
    purpose1
    purpose2
    purpose3
    purpose4
  )
  attr_accessor(*ATTRIBUTES)

  def matches
    t = ::Technique.arel_table
    u = ::Function.arel_table
    v = ::Part.arel_table
    
    results = ::Technique.all

    #results = results.where(purpose1: true) if value_to_boolean(purpose1)
    #results = results.where(purpose2: true) if value_to_boolean(purpose2)
    #results = results.where(purpose3: true) if value_to_boolean(purpose3)
    #results = results.where(purpose4: true) if value_to_boolean(purpose4)

    #results = results.where(contains(t[:categories_id], categories_id)) if categories_id.present?
    #results = results.where("categories_id = 1")# if categories_id.present?
    #results = results.where(t[:categories_id] == categories_id) if categories_id.present?

    ##results = results.where(contains(t[:title], title)) if title.present?

    #results = results.where(contains(t[:text1], text) | contains(t[:text2], text)) if text.present?

    ##results = results.where(t[:categories_id].matches(categories_id)) if categories_id.present?
    results
  end
end

app/models/technique.rb
class Technique < ActiveRecord::Base
  belongs_to :function
  belongs_to :part
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/setting_controller.rb
class SettingController < ApplicationController
  def index
  end

  def set
  end
end

app/controllers/techniques_controller.rb
class TechniquesController < ApplicationController
  before_action :set_technique, only: [:show, :edit, :update, :destroy]

  # GET /functions
  # GET /functions.json
  def index
    @techniques = Technique.all
    #@q = Technique.search
    #@q = Function.ransack(params[:q])
    #@functions = @q.result

    #@technique = Technique.new
    @technique = Search::Technique.new
    @techniques = @technique
                      .matches
    #@technique = @technique.
  end

  # GET /functions/1
  # GET /functions/1.json
  def show
    #@parts = Part.find_by(id: @technique.part_id)
    @parts = Part.find(@technique.part_id)
  end

  # GET /functions/new
  def new
    @technique = Technique.new
  end

  # GET /functions/1/edit
  def edit
  end

  #search
  #def search
  #  @q = Technique.search(params[:q])
  #  @techniques = @q
        #.result
        #.order(availability: :desc, code: :asc)
        #.decorate
  #end

  def search
    @technique = Search::Technique.new(search_params)
    @techniques = @technique
                     .matches
    #.order(availability: :desc, code: :asc)
    #.decorate
  end

  # POST /functions
  # POST /functions.json
  def create
    @technique = Technique.new(technique_params)

    respond_to do |format|
      if @technique.save
        format.html { redirect_to @technique, notice: 'Function was successfully created.' }
        format.json { render :show, status: :created, location: @technique }
      else
        format.html { render :new }
        format.json { render json: @technique.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /functions/1
  # PATCH/PUT /functions/1.json
  def update
    respond_to do |format|
      if @technique.update(technique_params)
        format.html { redirect_to @technique, notice: 'Function was successfully updated.' }
        format.json { render :show, status: :ok, location: @technique }
      else
        format.html { render :edit }
        format.json { render json: @technique.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /functions/1
  # DELETE /functions/1.json
  def destroy
    @technique.destroy
    respond_to do |format|
      format.html { redirect_to techniques_url, notice: 'Function was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_technique
      @technique = Technique.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def technique_params
      #params.require(:technique).permit(:name, :function_id, :part_id, :note, :adv_text, :sh_text)

      params.fetch(:technique, {})
      params.require(:technique).permit(:name, :function_id, :part_id, :note, :adv_text, :sh_text)
    end

    def search_params
      #search_conditions = %i(
      #  purpose1
      #)
      #params.require(:q).permit(search_conditions)
      params
          .require(:search_technique)
          .permit(Search::Technique::ATTRIBUTES)
    end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/functions_helper.rb
module FunctionsHelper
end

app/helpers/setting_helper.rb
module SettingHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/layouts/_header.html.erb
# coding: utf-8
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "S1322009", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
       <li><%=link_to "ABOUT",setting_index_path %></li>
       <li><%=link_to "SEARCH", techniques_path %></li>
       <li><%=link_to "FAV", techniques_path %></li>
       <li><%=link_to "TRIAL",root_path %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
# coding: utf-8
<!DOCTYPE html>
<html>
<head>
  <title>S1322009</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

 <%= render 'layouts/header' %>
 <div class="container">
   <div class="row">
     <br><br><br>
   </div>
   <div class="row">
     <% flash.each do |name, msg| %>
         <div class="alert alert-<%= name == "notice" ? "success" : "error" %>">
           <a class="close" data-dismiss="alert">×</a>
           <%= msg %>
         </div>
     <% end %>
     <div class="span8">
       <%= yield %>
     </div>
   </div>
 </div>

</body>
</html>

app/views/setting/index.html.erb
<h1>Setting#index</h1>
<p>Find me in app/views/setting/index.html.erb</p>

app/views/setting/set.html.erb
<h1>Setting#set</h1>
<p>Find me in app/views/setting/set.html.erb</p>

app/views/shared/_search_box.html.erb
<div class="panel panel-default">

  <div class="panel-heading">
    <h1 class="panel-title"><i class="fa fa-search"></i> 検索条件</h1>
  </div>
  <div class="panel-body">
    <%= yield %>
  </div>
</div>

app/views/techniques/_form.html.erb
<%= form_for(@technique) do |f| %>
  <% if @technique.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@technique.errors.count, "error") %> prohibited this function from being saved:</h2>

      <ul>
      <% @function.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :function_id %><br>
    <%= f.number_field :function_id %>
  </div>
  <div class="field">
    <%= f.label :part_id %><br>
    <%= f.number_field :part_id %>
  </div>
  <div class="field">
    <%= f.label :note %><br>
    <%= f.text_area :note %>
  </div>
  <div class="field">
    <%= f.label :adv_text %><br>
    <%= f.text_area :adv_text %>
  </div>
  <div class="field">
    <%= f.label :sh_text %><br>
    <%= f.text_area :sh_text %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/techniques/_result.erb
<%#= page_entries_info @technique %>

<% @techniques.each do |technique| %>
    <ul class="list-group">
      <%= link_to technique, class: 'list-group-item' do %>
        <h5><%= technique.name %></h5><br>
      <% end %>
      <li class="list-group-item">
        <div class="btn-group" role="group">
          <%= link_to technique, class: 'btn btn-default' do %>参照する<% end %>
          <%= link_to edit_technique_path(technique), class: 'btn btn-default' do %>編集する<% end %>
          <%= link_to technique, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' do %>消去する<% end %>
        </div>
      </li>
    </ul>
<% end %>

<%#= paginate @technique %>

app/views/techniques/_search_form.html.erb
<%= render layout: 'shared/search_box' do %>

  <%#= search_form_for(@q, url: search_techniques_path, html: { method: :get, class: 'form-horizontal', role: 'form' }) do |f| %>
  <%= form_for(@technique, url: search_techniques_path, html: { method: :get, class: 'form-horizontal', role: 'form' }) do |f| %>
    <div class="row">
      <ul class="nav nav-tabs">
        <li class="active"><a href="#sampleContentA" data-toggle="tab">目的</a></li>
        <li><a href="#sampleContentB" data-toggle="tab">特性</a></li>
        <li><a href="#sampleContentC" data-toggle="tab">オプション</a></li>
      </ul>

      <div class="tab-content">
        <div class="tab-pane active" id="sampleContentA">
          <div class="row">
            <div class="col-sm-1">
              <!-- 調整用です -->
            </div>
            <div class="col-sm-5">
              <div class="row">
                <div class="form-group">
                  <%= f.check_box :purpose1 %><%= f.label :purpose1, 'セキュリティ' %>
                </div>
                <div class="form-group">
                  <%= f.check_box :purpose2 %><%= f.label :purpose2, 'コスト削減' %>
                </div>
                <div class="form-group">
                  <%= f.check_box :purpose3 %><%= f.label :purpose3, '利便性' %>
                </div>
                <div class="form-group">
                  <%= f.check_box :purpose4 %><%= f.label :purpose4, '品質' %>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="tab-pane" id="sampleContentB">
          <div class="row">
            <div class="col-sm-1">
              <!-- 調整用です -->
            </div>
            <div class="col-sm-5">
              操作性
              <div class="btn-group" data-toggle="buttons">
                <label class="btn btn-default active">
                  <input type="radio" autocomplete="off" checked> 低
                </label>
                <label class="btn btn-default">
                  <input type="radio" autocomplete="off"> 中
                </label>
                <label class="btn btn-default">
                  <input type="radio" autocomplete="off"> 高
                </label>
              </div>
              導入コスト
              <div class="btn-group" data-toggle="buttons">
                <label class="btn btn-default active">
                  <input type="radio" autocomplete="off" checked> 低
                </label>
                <label class="btn btn-default">
                  <input type="radio" autocomplete="off"> 中
                </label>
                <label class="btn btn-default">
                  <input type="radio" autocomplete="off"> 高
                </label>
              </div>
              拡張性
              <div class="btn-group" data-toggle="buttons">
                <label class="btn btn-default active">
                  <input type="radio" autocomplete="off" checked> 低
                </label>
                <label class="btn btn-default">
                  <input type="radio" autocomplete="off"> 中
                </label>
                <label class="btn btn-default">
                  <input type="radio" autocomplete="off"> 高
                </label>
              </div>
              運用性
              <div class="btn-group" data-toggle="buttons">
                <label class="btn btn-default active">
                  <input type="radio" autocomplete="off" checked> 低
                </label>
                <label class="btn btn-default">
                  <input type="radio" autocomplete="off"> 中
                </label>
                <label class="btn btn-default">
                  <input type="radio" autocomplete="off"> 高
                </label>
              </div>
              機能性
              <div class="btn-group" data-toggle="buttons">
                <label class="btn btn-default active">
                  <input type="radio" autocomplete="off" checked> 低
                </label>
                <label class="btn btn-default">
                  <input type="radio" autocomplete="off"> 中
                </label>
                <label class="btn btn-default">
                  <input type="radio" autocomplete="off"> 高
                </label>
              </div>
            </div>
          </div>
        </div>
        <div class="tab-pane" id="sampleContentC">
          <div class="row">
            <div class="col-sm-1">
              <!-- 調整用です -->
            </div>
            <div class="col-sm-10">
              言語<br>
              <div class="btn-group" data-toggle="buttons">
                <label class="btn btn-default">
                  <input type="radio" autocomplete="off"> C
                </label>
                <label class="btn btn-default">
                  <input type="radio" autocomplete="off"> Ruby
                </label>
                <label class="btn btn-default">
                  <input type="radio" autocomplete="off"> Python
                </label>
                <label class="btn btn-default">
                  <input type="radio" autocomplete="off"> Java
                </label>
              </div>
              <br>
              プロトコル<br>
              <div class="btn-group" data-toggle="buttons">
                <label class="btn btn-default">
                  <input type="radio" autocomplete="off"> OpenFlow
                </label>
                <label class="btn btn-default">
                  <input type="radio" autocomplete="off"> NETCONF
                </label>
                <label class="btn btn-default">
                  <input type="radio" autocomplete="off"> OVSDB
                </label>
              </div>
              <br>
              環境<br>
              <div class="btn-group" data-toggle="buttons">
                <label class="btn btn-default">
                  <input type="radio" autocomplete="off"> VirtualBox
                </label>
                <label class="btn btn-default">
                  <input type="radio" autocomplete="off"> VMWare
                </label>
              </div>
            </div>

          </div>
        </div>
      </div>

    <br>
    <div class="col-sm-12 row text-center">
      <%= link_to techniques_path, class: 'btn btn-default btn-left' do %>クリア<% end %>
      <button class="btn btn-default btn-primary" type="submit"><i class="fa fa-search"></i> 検索</button>
      <br>
    </div>

    </div>
  <% end %>
<% end %>

app/views/techniques/edit.html.erb
<h1>Editing Function</h1>

<%= render 'form' %>

<%= link_to 'Show', @function %> |
<%= link_to 'Back', techniques_path %>

app/views/techniques/index.html.erb
<!-- <p id="notice"><%= notice %></p> -->

<table>

  <div class="col-md-4">
    <%= render 'search_form'%>

    <%= link_to 'New Function', new_technique_path %>
  </div>

  <div class="col-md-1">
    <!-- 調整用です -->
  </div>

  <div class="col-md-8">
    <%#= render 'result'%>
  </div>
</table>

<br>

app/views/techniques/new.html.erb
<h1>New Function</h1>

<%= render 'form' %>

<%= link_to 'Back', techniques_path %>

app/views/techniques/search.html.erb
<!-- <p id="notice"><%= notice %></p> -->

<table>

  <div class="col-md-4">
    <%= render 'search_form'%>

    <%= link_to 'New Function', new_technique_path %>
  </div>

  <div class="col-md-1">
    <!-- 調整用です -->
  </div>

  <div class="col-md-8">
    <%= render 'result'%>
  </div>
</table>

<br>

app/views/techniques/show.html.erb
<!--<p id="notice"><%= notice %></p> -->

<h1><%= @technique.name %></h1>

<p>

<div class="panel panel-default">
	<div class="panel-heading">
		<%= @parts.name %>の特徴
	</div>
	<div class="panel-body">
		<%= @parts.note1 %>
	</div>
</div>

<div class="panel panel-default">
	<div class="panel-heading">
		長所・短所
	</div>
	<div class="panel-body">
		<strong>長所</strong><br>
		<%= @technique.adv_text %><br>
		<strong>短所</strong><br>
		<%= @technique.sh_text %><br>
	</div>
</div>

<div class="panel panel-default">
	<div class="panel-heading">
		実装方法
	</div>
	<div class="panel-body">
		<%= @parts.note2 %>
		<%= @technique.note %>
	</div>
</div>

</p>

<%#= link_to 'Edit', edit_technique_path(@technique) %>
<%#= link_to 'Back', techniques_path %>

<%= link_to techniques_path, class: 'btn btn-default' do %>戻る<% end %>

app/views/top/index.html.erb
<h1>卒業研究1</h1>

<%= link_to techniques_path, class: 'btn btn-primary btn-center btn-lg' do %>始める<% end %>

<br>